project_id = "oruiwhdxkouceyiglumc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false